// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function $$default(ctx) {
  var res = {
    body: {
      message: "Hello world!"
    }
  };
  ctx.res = res;
  ctx.done();
  return /* () */0;
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* No side effect */
